name: Deploy to Fly.io
on:
  push:
    branches:
      - main  # Altere para "master" se a sua ramificação principal tiver esse nome

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --app bott-de-automoção
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
